---
- name: Validate Multi-OS Baseline
  hosts: all
  gather_facts: true

  tasks:

    - name: Display OS Family
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} uses {{ ansible_facts['os_family'] }}"

    - name: Linux disk usage check
      ansible.builtin.command: df -h /
      register: linux_disk_output
      when: ansible_facts['os_family'] != "Windows"

    - name: Show Linux disk usage
      ansible.builtin.debug:
        var: linux_disk_output.stdout_lines
      when: ansible_facts['os_family'] != "Windows"

    - name: Windows disk usage check
      ansible.windows.win_shell: |
        Get-PSDrive C
      register: windows_disk_output
      when: ansible_facts['os_family'] == "Windows"

    - name: Show Windows disk usage
      ansible.builtin.debug:
        var: windows_disk_output.stdout_lines
      when: ansible_facts['os_family'] == "Windows"
