aws_region    = "ap-south-1"
ami_id        = "ami-0f5ee92e2d63afc18"
instance_type = "t2.micro"
instance_name = "remote-backend-demo-server"
environment   = "practice"
key_pair_name = "terraform-practice-key"
