[ubuntu]
ubuntu-1 ansible_host=13.206.239.46

[amazon_linux]
amazon-linux-1 ansible_host=43.204.25.145

[rhel]
rhel-1 ansible_host=13.232.43.14

[windows]
windows-1 ansible_host=15.206.73.174

[linux:children]
ubuntu
amazon_linux
rhel
